### ISSUE TITLE
Will this plugin support Neovim 0.8+?

### ISSUE THREAD

**Issue by ihaohe** [LiadOz/nvim-dap-repl-highlights#3]

**Comment by LiadOz** [comment]
Neovim 0.8 and previous versions have an issue with the prompt buffer extmarks. As part of developing this plugin I have fixed that issue here https://github.com/neovim/neovim/pull/21331, the fix didn't get added to the 0.8 releases. Since this fix is in the core Neovim code, there is not much that can be done in lua.

**Comment by ihaohe** [comment]
Thanks for your reply.
